name: workflows-servicios

on: [push]

jobs: 
  trabajo1:
    runs-on: ubuntu-latest
  
    steps:
      - name: Darwin
        uses: actions/checkout@v2
      - name: listar archivos
        run: ls -la